# Site settings
title: Alex Pearce
email: alex@alexpearce.me
description: >
  Blog of physicist and developer Alex Pearce.
baseurl: ""
url: "https://alexpearce.me"
permalink: /:year/:month/:title/
twitter_username: alxprc
github_username:  alexpearce

markdown: kramdown

# Minify output CSS
sass:
  style: compressed

# These files aren't part of the build
exclude: [Gemfile, Gemfile.lock, README.md, config, vendor]
# Needed for Netlify redirects
include: [_redirects]

paginate: 8
paginate_path: "/blog/page:num/"

plugins: [jekyll-paginate]
