# http://jekyllrb.com/docs/configuration/

# Don't use custom plugins
safe: true

baseurl: /
url: http://localhost:4000

# Site source
source: .
# Where to put the compiled site
destination: ./_site
# Markdown engine
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]
# Use Pygments for syntax highlighting
highlighter: rouge

# Exclude these files from compilation
exclude: [Gemfile, Gemfile.lock, README.md, vendor, bin]

# Don't produce a 'related posts' index
lsi: false

# Permalink style
permalink: /:year/:month/:title
