[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-no-more-404"

  [plugins.inputs]
  # change this key to a new one any time you need to restart from scratch
  cacheKey = "2020-06-19"
